// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.i377.team28.entities;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SEOTUD_KONTAKTISIK_Roo_Configurable {
    
    declare @type: SEOTUD_KONTAKTISIK: @Configurable;
    
}
