// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.i377.team28.web;

import org.slf4j.Logger;

privileged aspect AndmedBaasi_Roo_JavaBean {
    
    public Logger AndmedBaasi.getLog() {
        return this.log;
    }
    
}
